/* Admin portal data bridge: live CRUD for the core management screens. */
(() => {
  const A=window.UPSC_API; if(!A)return;
  const page=location.pathname.split('/').pop()||'index.html';
  const adminPages=new Set(['admin-dashboard.html','student-management.html','question-bank-admin.html','test-management-admin.html','test-series-management-admin.html','results-admin.html','subscriptions-admin.html','payments-admin.html','coupons-admin.html','notifications-admin.html','reports-admin.html','settings-admin.html','current-affairs-admin.html','study-material-admin.html','blog-admin.html']);
  const $=id=>document.getElementById(id); const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  async function me(){try{const u=await A.get('/auth/me');if(!['admin','super_admin','content_manager','evaluator','finance','support'].includes(u.role)){location.href='login.html';return null;}document.querySelectorAll('.profile-name').forEach(e=>e.textContent=`${u.first_name}${u.last_name?' '+u.last_name:''}`);document.querySelectorAll('.profile-sub').forEach(e=>e.textContent=u.role.replace('_',' '));return u;}catch(_){A.clearSession();location.href='login.html';return null;}}
  function logout(){document.querySelectorAll('#logoutBtn').forEach(btn=>{const clone=btn.cloneNode(true);btn.replaceWith(clone);clone.addEventListener('click',()=>{A.clearSession();location.href='login.html';});});}
  async function students(){const rows=await A.get('/admin/students');const body=$('studentRows');if(!body)return;body.innerHTML=rows.map(r=>`<tr><td><strong>${esc(r.first_name)} ${esc(r.last_name||'')}</strong><div class="subtext">${esc(r.email||r.mobile||'')}</div></td><td>${esc(r.role==='student'?'Student':r.role)}</td><td><span class="pill ${r.status==='active'?'green':'gray'}">${esc(r.status)}</span></td><td>—</td><td>—</td><td>${esc(r.last_login_at?new Date(r.last_login_at).toLocaleDateString('en-IN'):'Never')}</td><td>${esc(r.created_at?new Date(r.created_at).toLocaleDateString('en-IN'):'')}</td><td><button class="icon-btn" data-student-status="${r.id}" title="Toggle active status">${r.status==='active'?'⏸':'▶'}</button></td></tr>`).join('');setText('resultCount',`${rows.length} students`);body.querySelectorAll('[data-student-status]').forEach(b=>b.addEventListener('click',async()=>{const row=rows.find(x=>x.id===b.dataset.studentStatus);await A.put(`/admin/students/${row.id}`,{status:row.status==='active'?'inactive':'active'});students();}));}
  function setText(id,v){const e=$(id);if(e)e.textContent=v;}
  const subjectMap={Polity:'polity',Economy:'economy',History:'history',Geography:'geography',Environment:'environment','Science & Technology':'science',Current:'current',CSAT:'csat',Governance:'polity'};
  const topicMap={Parliament:'polity-parliament','Fundamental Rights':'polity-rights','Monetary Policy':'economy-monetary',Biodiversity:'environment-biodiversity'};
  function fillQuestionForm(q){if(!$('qText'))return;$('qText').value=q.stem||'';$('qSubject').value=q.subject_name||'Polity';$('qTopic').value=q.topic_name||'Parliament';$('qDifficulty').value=(q.difficulty||'moderate').replace(/^./,m=>m.toUpperCase());$('optA').value=q.option_a||'';$('optB').value=q.option_b||'';$('optC').value=q.option_c||'';$('optD').value=q.option_d||'';$('qAnswer').value=q.correct_option||'A';$('qExplanation').value=q.explanation||'';$('qSource').value=q.source||'';}
  async function questions(){const rows=await A.get('/admin/questions');const body=$('questionRows');if(!body)return;body.innerHTML=rows.map(q=>`<tr><td><strong>${esc(q.id)}</strong></td><td><div class="q-preview">${esc(q.stem)}</div></td><td>${esc(q.subject_name||'—')}</td><td>${esc(q.topic_name||'—')}</td><td>${esc(q.difficulty||'')}</td><td>${esc(q.status)}</td><td>${esc(q.upsc_year||'—')}</td><td><button class="iconbtn" data-edit-q="${q.id}">✎</button><button class="iconbtn" data-delete-q="${q.id}">⌫</button></td></tr>`).join('');setText('resultCount',`${rows.length} questions`);body.querySelectorAll('[data-edit-q]').forEach(b=>b.addEventListener('click',()=>{const q=rows.find(x=>x.id===b.dataset.editQ);window.editingId=q.id;fillQuestionForm(q);$('modalTitle').textContent='Edit Question';$('questionOverlay').classList.add('show');}));body.querySelectorAll('[data-delete-q]').forEach(b=>b.addEventListener('click',async()=>{if(confirm('Delete this question?')){await A.del(`/admin/questions/${b.dataset.deleteQ}`);questions();}}));}
  function slugify(s){return String(s).toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
  async function seriesList(){const rows=await A.get('/admin/series');const body=$('seriesRows');if(!body)return;body.innerHTML=rows.map(s=>`<tr><td><strong>${esc(s.name)}</strong><div class="subtext">${esc(s.slug)}</div></td><td>—</td><td>${s.test_count||0}</td><td>—</td><td>₹${(s.price_paise/100).toLocaleString('en-IN')}</td><td>—</td><td>${s.price_paise?'Premium':'Free'}</td><td>${esc(s.status)}</td><td>—</td><td><button class="iconbtn" data-series="${s.id}">✎</button></td></tr>`).join('');setText('resultCount',`${rows.length} series`);}
  function hookQuestionSave(){window.saveQuestion=async(status)=>{try{const body={subject_id:subjectMap[$('qSubject').value]||'polity',topic_id:topicMap[$('qTopic').value]||'polity-parliament',stem:$('qText').value.trim(),option_a:$('optA').value.trim(),option_b:$('optB').value.trim(),option_c:$('optC').value.trim(),option_d:$('optD').value.trim(),correct_option:$('qAnswer').value,explanation:$('qExplanation').value.trim(),difficulty:$('qDifficulty').value.toLowerCase(),source:$('qSource').value.trim(),status:status==='publish'?'published':'draft'};if(!body.stem)throw new Error('Question text is required');if(window.editingId)await A.put(`/admin/questions/${window.editingId}`,body);else await A.post('/admin/questions',body);window.editingId=null;if(window.closeModal)closeModal('questionOverlay');else $('questionOverlay')?.classList.remove('show');await questions();}catch(e){alert(e.message)}};}
  function hookSeries(){window.saveSeries=async(status)=>{try{const name=$('seriesName').value.trim();if(!name)throw new Error('Series name is required');await A.post('/admin/series',{name,slug:slugify(name),description:$('seriesDescription').value.trim(),price_paise:Math.round(parseFloat(($('seriesPrice').value||'0').replace(/[^0-9.]/g,''))*100),validity_days:365,status,featured:false});if(window.closeSeries)closeSeries();await seriesList();}catch(e){alert(e.message)}};}
  async function dashboard(){const d=await A.get('/admin/dashboard');const main=document.querySelector('.main .container');if(main&&!document.getElementById('liveAdminMetrics')){const bar=document.createElement('div');bar.id='liveAdminMetrics';bar.style.cssText='margin:0 0 18px;padding:12px 16px;border:1px solid #dce5ef;background:#f8fbff;border-radius:12px;font-size:11px;font-weight:800;color:#10243e;display:flex;gap:18px;flex-wrap:wrap';bar.innerHTML=`<span>Live: ${d.students} students</span><span>${d.questions} questions</span><span>${d.tests} tests</span><span>${d.attempts} completed attempts</span><span>${d.series} test series</span>`;main.prepend(bar);}}
  function injectLiveNote(target, text){if(!target)return;const n=document.createElement('div');n.className='live-api-note';n.style.cssText='margin:0 0 14px;padding:10px 13px;border:1px solid #d9e8f8;background:#f7fbff;border-radius:10px;color:#31506f;font-size:11px;font-weight:800;';n.textContent='LIVE API · '+text;target.parentNode.insertBefore(n,target);}
  function fmtINR(p){return '₹'+(Number(p||0)/100).toLocaleString('en-IN',{maximumFractionDigits:0});}
  async function commerce(){
    if(page==='subscriptions-admin.html'){
      const root=document.querySelector('.content'); const live=document.createElement('div'); live.className='table-card'; live.innerHTML='<div class="card-head"><h2>Live Subscription Data</h2><span class="muted">Loaded from API</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Student</th><th>Plan</th><th>ID</th><th>Start</th><th>Expiry</th><th>Value</th><th>Status</th></tr></thead><tbody id="liveSubRows"></tbody></table></div>'; root.insertBefore(live,document.querySelector('.table-card')||null); const rows=await A.get('/admin/subscriptions'); const body=live.querySelector('#liveSubRows'); body.innerHTML=rows.map(r=>`<tr><td><strong>${esc(r.first_name)} ${esc(r.last_name||'')}</strong><div class="subtext">${esc(r.email||'')}</div></td><td>${esc(r.plan_name)}</td><td>${esc(r.id)}</td><td>${new Date(r.starts_at).toLocaleDateString('en-IN')}</td><td>${new Date(r.expires_at).toLocaleDateString('en-IN')}</td><td>${fmtINR(r.price_paise)}</td><td><span class="pill ${r.status==='active'?'green':r.status==='cancelled'?'red':'amber'}">${esc(r.status)}</span></td></tr>`).join('') || '<tr><td colspan="7">No subscriptions yet.</td></tr>';
      const plans=await A.get('/admin/plans'); const panel=document.getElementById('plansPanel'); if(panel){panel.querySelectorAll('.plan-card').forEach((card,i)=>{const plan=plans[i]; if(!plan)return; const price=card.querySelector('.price'); if(price) price.innerHTML=`${fmtINR(plan.price_paise)} <small>/ ${plan.validity_days} days</small>`; const metrics=card.querySelectorAll('.metric strong'); if(metrics[0]) metrics[0].textContent=Number(plan.active_subscribers||0).toLocaleString('en-IN'); if(metrics[1]) metrics[1].textContent=fmtINR(Number(plan.price_paise)*(Number(plan.successful_payments||0)));});}
      injectLiveNote(live,'subscription records and plan metrics are connected.');
    }
    if(page==='payments-admin.html'){/* the page loads its own live data and refund flow */}
    if(page==='coupons-admin.html'){const rows=await A.get('/admin/coupons'); const body=document.querySelector('#couponTable tbody'); if(body){body.innerHTML=rows.map(r=>`<tr data-status="${esc(r.status)}" data-type="${esc(r.discount_type)}"><td><strong>${esc(r.code)}</strong></td><td>${esc(r.campaign||'')}</td><td>${esc(r.discount_type==='percentage'?r.value+'%':fmtINR(r.value))}</td><td>${esc(r.applies_to)}</td><td>${esc((r.starts_at||'').slice(0,10))} → ${esc((r.ends_at||'').slice(0,10))}</td><td>${Number(r.redemptions||0)}</td><td>${r.redemption_limit||'∞'}</td><td><span class="pill ${r.status==='active'?'green':r.status==='expired'?'red':r.status==='scheduled'?'amber':'gray'}">${esc(r.status)}</span></td><td><button class="btn btn-ghost" data-live-coupon="${r.id}">Manage</button></td></tr>`).join('')||'<tr><td colspan="9">No coupons yet.</td></tr>'; body.querySelectorAll('[data-live-coupon]').forEach(b=>b.addEventListener('click',()=>alert('Coupon management is connected to the API.')));}
    }
    if(page==='notifications-admin.html'){const rows=await A.get('/admin/notifications'); const body=document.querySelector('#notifTable tbody'); if(body){body.innerHTML=rows.map(r=>`<tr data-status="Sent" data-channel="In-app" data-type="${esc(r.type)}" data-aud="All Students"><td><strong>${esc(r.title)}</strong><div class="subtext">${new Date(r.created_at).toLocaleString('en-IN')}</div></td><td><span class="pill blue">${esc(r.type)}</span></td><td>In-app</td><td>All Students</td><td>${new Date(r.created_at).toLocaleString('en-IN')}</td><td>${r.delivered||0}</td><td>${r.read_count||0}</td><td><span class="pill green">Sent</span></td><td><button class="btn btn-ghost" onclick="viewStats('live')">Analytics</button></td></tr>`).join('')||'<tr><td colspan="9">No notifications yet.</td></tr>';}}
    if(page==='reports-admin.html'){const r=await A.get('/admin/reports/summary'); const grid=document.getElementById('reportGrid'); if(grid){const live=document.createElement('div'); live.className='panel'; live.style.margin='0 0 16px'; live.innerHTML=`<div class="panel-head"><div><h2>Live Platform Snapshot</h2><p>Calculated from the development database.</p></div><span class="pill green">API Connected</span></div><div class="stats-grid"><div class="stat"><div class="label">Students</div><div class="value">${r.students.toLocaleString('en-IN')}</div></div><div class="stat"><div class="label">Attempts</div><div class="value">${r.attempts.toLocaleString('en-IN')}</div></div><div class="stat"><div class="label">Successful Payments</div><div class="value">${r.successful_payments.toLocaleString('en-IN')}</div></div><div class="stat"><div class="label">Net Collections</div><div class="value">${fmtINR(r.net_paise)}</div></div></div>`; grid.parentNode.insertBefore(live,grid);}}
    if(page==='settings-admin.html'){const rows=await A.get('/admin/settings'); const map=Object.fromEntries(rows.map(x=>[x.key,x.value])); const setRow=(sel,val)=>{const r=document.querySelector(sel); if(!r)return; const el=r.querySelector('input,select'); if(el && val!==undefined && el.type!=='checkbox') el.value=val; if(r.querySelector('.switch') && val!==undefined) r.querySelector('.switch').classList.toggle('on',String(val)==='true');}; setRow('#general .row:nth-child(1)',map.platform_name); setRow('#general .row:nth-child(2)',map.support_email); setRow('#general .row:nth-child(3)',map.timezone); setRow('#general .row:nth-child(4)',map.maintenance_mode); setRow('#tests .row:nth-child(1)',map.default_negative_marking); setRow('#tests .row:nth-child(2)',map.auto_save_answers); setRow('#tests .row:nth-child(3)',map.auto_submit_timeout); setRow('#tests .row:nth-child(4)',map.allow_retakes); setRow('#tests .row:nth-child(5)',map.result_publication); setRow('#access .row:nth-child(1)',map.session_timeout); setRow('#access .row:nth-child(2)',map.student_otp); setRow('#access .row:nth-child(3)',map.admin_2fa); setRow('#access .row:nth-child(4)',map.api_rate_limit); const save=document.querySelector('[onclick="saveAll()"]'); if(save) { save.textContent='Save Changes · API'; window.saveAll=async()=>{const val=(section,idx)=>{const r=document.querySelectorAll(`#${section} .row`)[idx]; if(!r)return ''; const el=r.querySelector('input,select'); if(el)return el.value; const sw=r.querySelector('.switch'); return sw?.classList.contains('on')?'true':'false';}; const pairs={platform_name:val('general',0),support_email:val('general',1),timezone:val('general',2),maintenance_mode:val('general',3),default_negative_marking:val('tests',0),auto_save_answers:val('tests',1),auto_submit_timeout:val('tests',2),allow_retakes:val('tests',3),result_publication:val('tests',4),session_timeout:val('access',0),student_otp:val('access',1),admin_2fa:val('access',2),api_rate_limit:val('access',3)}; try{for(const [k,v] of Object.entries(pairs)) await A.put('/admin/settings',{key:k,value:String(v)}); alert('Settings saved to the API.');}catch(e){alert(e.message)}}; }}
  }
  async function run(){const u=await me();if(!u)return;logout();try{if(page==='student-management.html')await students();else if(page==='question-bank-admin.html'){hookQuestionSave();window.reloadAdminQuestions=questions;await questions();}else if(page==='test-management-admin.html'){/* the page loads its own live data */}else if(page==='test-series-management-admin.html'){hookSeries();await seriesList();}else if(page==='admin-dashboard.html')await dashboard();await commerce();}catch(e){console.warn('Admin API bridge',e)}}
  window.sendTestEmail=async function(){const btn=document.getElementById('testEmailBtn'),hint=document.getElementById('testEmailHint'),to=document.getElementById('testEmailTo').value.trim();if(!btn||!hint)return;btn.disabled=true;const prev=hint.textContent;hint.textContent='Sending...';try{const r=await A.post('/admin/notifications/test-email',to?{to}:{});hint.textContent='Sent to '+r.to+'. Check that inbox (and spam folder).';hint.style.color='#067647'}catch(e){hint.textContent=e.message||'Could not send the test e-mail.';hint.style.color='#b42318'}finally{btn.disabled=false;setTimeout(()=>{hint.textContent=prev;hint.style.color=''},6000)}};
  if(adminPages.has(page)) run();
})();
