(() => {
  const A=window.UPSC_API; if(!A)return;
  const page=location.pathname.split('/').pop();
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const $=id=>document.getElementById(id);
  const toast=msg=>{const t=$('toast');if(t){t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}else alert(msg)};
  const close=id=>$(id)?.classList.remove('show');
  const slugify=s=>String(s).toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');

  async function adminGuard(){try{const u=await A.get('/auth/me');if(!['admin','super_admin','content_manager'].includes(u.role)){location.href='login.html';return null;}return u}catch(e){location.href='login.html';return null}}
  async function currentAffairs(){const rows=await A.get('/admin/current-affairs');const body=$('articleRows');if(!body)return;body.innerHTML=rows.map(r=>`<tr><td><strong>${esc(r.title)}</strong><div class="subtext">${esc(r.id)}</div></td><td>${esc(r.category)}</td><td>${esc(r.gs||'—')}</td><td>${esc(r.month||'—')}</td><td>${r.published_at?new Date(r.published_at).toLocaleDateString('en-IN'):'—'}</td><td>${Number(r.featured)?'Yes':'—'}</td><td><span class="pill ${r.status==='published'?'green':r.status==='scheduled'?'amber':'gray'}">${esc(r.status)}</span></td><td><button class="btn btn-outline" data-edit-ca="${r.id}">Edit</button></td></tr>`).join('')||'<tr><td colspan="8">No current-affairs records.</td></tr>';setText('resultCount',`${rows.length} articles`);body.querySelectorAll('[data-edit-ca]').forEach(b=>b.onclick=()=>{const r=rows.find(x=>x.id===b.dataset.editCa);$('modalTitle').textContent='Edit Current Affairs';window.cmsEditId=r.id;[['title',r.title],['category',r.category],['gs',r.gs],['pubDate',r.published_at?.slice(0,16)],['author',r.author],['summary',r.summary],['editor',r.key_points],['source',r.source]].forEach(([id,v])=>{if($(id))$(id).value=v||''});if($('featured'))$('featured').checked=!!r.featured;if($('mcqLink'))$('mcqLink').value=r.mcq_link||'';if($('revision'))$('revision').checked=!!r.revision;if($('seo'))$('seo').checked=!!r.seo;$('articleOverlay')?.classList.add('show')});}
  async function saveCA(status){const body={title:$('title').value.trim(),category:$('category').value.trim(),gs:$('gs')?.value||'',month:new Date($('pubDate')?.value||Date.now()).toLocaleString('en-US',{month:'long',year:'numeric'}),published_at:$('pubDate')?.value?new Date($('pubDate').value).toISOString():new Date().toISOString(),minutes:5,summary:$('summary').value.trim(),key_points:$('editor')?.value||'',status,author:$('author')?.value||'',source:$('source')?.value||'',featured:!!$('featured')?.checked,mcq_link:$('mcqLink')?.value||'',revision:!!$('revision')?.checked,seo:!!$('seo')?.checked,content:$('editor')?.innerText||''};if(!body.title||!body.category||!body.summary)return toast('Title, category and summary are required.');if(window.cmsEditId)await A.put(`/admin/current-affairs/${window.cmsEditId}`,body);else await A.post('/admin/current-affairs',body);window.cmsEditId=null;close('articleOverlay');toast(status==='published'?'Article published via API.':'Draft saved via API.');currentAffairs();}

  async function materials(){const rows=await A.get('/admin/study-material');const body=$('resourceRows');if(!body)return;body.innerHTML=rows.map(r=>`<tr><td><strong>${esc(r.title)}</strong><div class="subtext">${esc(r.id)}</div></td><td>${esc(r.subject)}</td><td>${esc(r.topic||'—')}</td><td>${esc(r.format)}</td><td>${esc(r.access_type)}</td><td>${esc(r.owner||'—')}</td><td>${esc(r.status)}</td><td><button class="btn btn-outline" data-edit-mat="${r.id}">Edit</button></td></tr>`).join('')||'<tr><td colspan="8">No study-material records.</td></tr>';setText('resultCount',`${rows.length} resources`);body.querySelectorAll('[data-edit-mat]').forEach(b=>b.onclick=()=>{const r=rows.find(x=>x.id===b.dataset.editMat);window.cmsEditId=r.id;[['title',r.title],['subject',r.subject],['topic',r.topic],['format',r.format],['owner',r.owner],['tags',r.tags],['source',r.source],['description',r.summary]].forEach(([id,v])=>{if($(id))$(id).value=v||''});if($('access'))$('access').value=r.access_type||'free';if($('featured'))$('featured').checked=!!r.featured;if($('track'))$('track').checked=!!r.track;if($('practice'))$('practice').value=r.practice||'';if($('seo'))$('seo').checked=!!r.seo;$('resourceOverlay')?.classList.add('show')});}
  async function saveMat(status){const body={title:$('title').value.trim(),subject:$('subject').value.trim(),topic:$('topic')?.value||'',format:$('format')?.value||'PDF',access_type:$('access')?.value||'free',pages:'',summary:$('description').value.trim(),status,owner:$('owner')?.value||'',tags:$('tags')?.value||'',source:$('source')?.value||'',featured:!!$('featured')?.checked,track:!!$('track')?.checked,practice:$('practice')?.value||'',seo:!!$('seo')?.checked,file_url:null};if(!body.title||!body.subject||!body.summary)return toast('Title, subject and description are required.');if(window.cmsEditId)await A.put(`/admin/study-material/${window.cmsEditId}`,body);else await A.post('/admin/study-material',body);window.cmsEditId=null;close('resourceOverlay');toast(status==='published'?'Resource published via API.':'Draft saved via API.');materials();}

  async function blogs(){const rows=await A.get('/admin/blog');const body=$('postRows');if(!body)return;body.innerHTML=rows.map(r=>`<tr><td><strong>${esc(r.title)}</strong><div class="subtext">${esc(r.slug)}</div></td><td>${esc(r.category||'—')}</td><td>${esc(r.format||'Article')}</td><td>${esc(r.author||'—')}</td><td>${r.published_at?new Date(r.published_at).toLocaleDateString('en-IN'):'—'}</td><td>${Number(r.featured)?'Featured':'—'}</td><td>${esc(r.status)}</td><td><button class="btn btn-outline" data-edit-blog="${r.id}">Edit</button></td></tr>`).join('')||'<tr><td colspan="8">No blog records.</td></tr>';setText('resultCount',`${rows.length} posts`);body.querySelectorAll('[data-edit-blog]').forEach(b=>b.onclick=()=>{const r=rows.find(x=>x.id===b.dataset.editBlog);window.cmsEditId=r.id;[['title',r.title],['excerpt',r.excerpt],['category',r.category],['author',r.author],['publishDate',r.published_at?.slice(0,16)],['image',r.image],['seoTitle',r.seo_title],['metaDescription',r.meta_description],['slug',r.slug]].forEach(([id,v])=>{if($(id))$(id).value=v||''});if($('editor'))$('editor').innerText=r.content||'';if($('featured'))$('featured').checked=!!r.featured;if($('newsletter'))$('newsletter').checked=!!r.newsletter;if($('revision'))$('revision').checked=!!r.revision;if($('allowComments'))$('allowComments').checked=!!r.allow_comments;$('postOverlay')?.classList.add('show')});}
  async function saveBlog(status){const title=$('title').value.trim();const body={title,slug:$('slug')?.value.trim()||slugify(title),excerpt:$('excerpt')?.value||'',category:$('category')?.value||'',author:$('author')?.value||'',status,published_at:$('publishDate')?.value?new Date($('publishDate').value).toISOString():new Date().toISOString(),format:$('format')?.value||'Article',image:$('image')?.value||'',seo_title:$('seoTitle')?.value||title,meta_description:$('metaDescription')?.value||'',featured:!!$('featured')?.checked,newsletter:!!$('newsletter')?.checked,related_tests:$('relatedTests')?.value||'',revision:!!$('revision')?.checked,allow_comments:!!$('allowComments')?.checked,content:$('editor')?.innerText||''};if(!title)return toast('Title is required.');if(window.cmsEditId)await A.put(`/admin/blog/${window.cmsEditId}`,body);else await A.post('/admin/blog',body);window.cmsEditId=null;close('postOverlay');toast(status==='published'?'Post published via API.':'Draft saved via API.');blogs();}

  async function contacts(){try{const rows=await A.get('/admin/support/enquiries');const tbody=document.querySelector('#supportRows');if(tbody)tbody.innerHTML=rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.email||'')}</td><td>${esc(r.subject)}</td><td><span class="pill ${r.status==='resolved'?'green':r.status==='in_progress'?'amber':'gray'}">${esc(r.status)}</span></td><td>${new Date(r.created_at).toLocaleDateString('en-IN')}</td></tr>`).join('')||'<tr><td colspan="5">No support enquiries.</td></tr>';}catch(e){}}

  function setText(id,v){const e=$(id);if(e)e.textContent=v}
  window.cmsSaveCurrentAffair=saveCA;window.cmsSaveMaterial=saveMat;window.cmsSaveBlog=saveBlog;
  async function publicCA(){const box=$('articleList');if(!box)return;const rows=await A.get('/public/current-affairs');if(!rows.length)return;box.innerHTML=rows.map(r=>`<article class="article" data-category="${esc((r.category||'').toLowerCase())}" data-subject="${esc((r.gs||'').toLowerCase().replace(/\s/g,''))}" data-search="${esc((r.title+' '+r.summary+' '+(r.key_points||'')).toLowerCase())}"><div class="article-top"><div class="chips"><span class="chip blue">${esc(r.category)}</span><span class="chip">${esc(r.gs||'UPSC')}</span></div><span class="article-date">${r.published_at?new Date(r.published_at).toLocaleDateString('en-IN'):''}</span></div><h3>${esc(r.title)}</h3><p>${esc(r.summary)}</p><div class="article-foot"><span class="tags">${esc(r.key_points||'')}</span><a class="read" href="current-affairs-detail.html?id=${encodeURIComponent(r.id)}">Read article →</a></div></article>`).join('');}
  async function publicMaterial(){const box=$('materialList');if(!box)return;const rows=await A.get('/public/study-material');if(!rows.length)return;box.innerHTML=rows.map(r=>`<article class="material-card" data-subject="${esc((r.subject||'').toLowerCase())}" data-format="${esc((r.format||'').toLowerCase())}" data-access="${esc(r.access_type)}" data-search="${esc((r.title+' '+r.summary+' '+(r.topic||'')).toLowerCase())}"><div class="top"><div class="chips"><span class="chip blue">${esc(r.subject)}</span><span class="chip">${esc(r.format)}</span></div><span class="access">${esc(r.access_type)}</span></div><h3>${esc(r.title)}</h3><p>${esc(r.summary)}</p><div class="material-meta"><span>${esc(r.pages||'')}</span><span>${esc(r.topic||'')}</span><span>${esc(r.access_type)}</span></div><div class="material-foot"><span class="chip ${r.access_type==='free'?'green':'gold'}">${r.access_type==='free'?'Free':'Premium'}</span><a class="resource-btn ${r.access_type==='free'?'':'premium'}" href="${r.access_type==='free'?(r.file_url||'#'):'login.html'}">${r.access_type==='free'?'View resource →':'Login to access →'}</a></div></article>`).join('');}
  async function publicBlog(){const box=$('articles');if(!box)return;const rows=await A.get('/public/blog');if(!rows.length)return;box.innerHTML=rows.map(r=>`<article class="blog-card"><div class="meta"><span>${esc(r.category||'UPSC')}</span><span>${r.published_at?new Date(r.published_at).toLocaleDateString('en-IN'):''}</span></div><h3>${esc(r.title)}</h3><p>${esc(r.excerpt||'')}</p><a href="blog-detail.html?slug=${encodeURIComponent(r.slug)}">Read article →</a></article>`).join('');}
  async function run(){if(page==='current-affairs-admin.html'){if(await adminGuard())currentAffairs()}else if(page==='study-material-admin.html'){if(await adminGuard())materials()}else if(page==='blog-admin.html'){if(await adminGuard())blogs()}else if(page==='current-affairs.html')publicCA();else if(page==='study-material.html')publicMaterial();else if(page==='blog.html')publicBlog();else if(page==='contact.html'){const form=$('contactForm');if(form)form.addEventListener('submit',async e=>{e.preventDefault();try{await A.post('/support/enquiries',{name:$('name').value,email:$('email').value,subject:$('subject').value,message:$('message').value});$('success')?.classList.add('show');form.reset()}catch(err){toast(err.message)}})}}
  run().catch(e=>console.warn('CMS bridge',e));
})();
